### ISSUE TITLE
Can't create a database with an hyphen in its name "foo-bar"

### ISSUE THREAD

**Issue by jeromenerf** [xyproto/simplehstore#1]
https://github.com/xyproto/simplehstore/blob/e2bf082ae1e61cbe950f2e2de5833e188173ba24/simplehstore.go#L176

```
    if _, err := host.db.Exec("CREATE DATABASE " + host.dbname + " WITH ENCODING '" + encoding + "'"); err != nil {
```

returns err : `Could not create database avisonline-dev: pq: syntax error at or near "-"` for "foo-bar"

Adding single quotes saves the day.

Perhaps using `fmt.Sprintf()` to  avoid the easy to miss `'" +`?

```
    if _, err := host.db.Exec(fmt.Sprintf("CREATE DATABASE '%s' WITH ENCODING '%s'", host.dbname, encoding)); err != nil {
```

**Comment by xyproto** [comment]
Thanks for reporting! Will fix.

**Comment by xyproto** [comment]
Added a test case that tries to use both `-` and `'` in the queries.

**Comment by xyproto** [comment]
Will switch over to use [this method](https://godoc.org/github.com/lib/pq#QuoteIdentifier) (`pg.QuoteIdentifier`) everywhere.

**Comment by xyproto** [comment]
`pq.QuoteIdentifier` did not help much. Will have to figure out a safe way to quote identifiers and values.

**Comment by xyproto** [comment]
Tests pass and the issue is fixed. Please confirm that it now works as expected.
